swagger: '2.0'
info:
  title: OONI Pipeline
  description: A public interface to the OONI Pipeline
  version: "1.0.0"
# the domain of the service
host: api.ooni.io
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /reports:
    get:
      summary: List reports
      description: |
        This will return all the OONI reports in the database
      parameters:
        - name: offset
          in: query
          type: integer
          format: int32
          description: Offset the list of returned results by this amount. Default is zero.
        - name: limit
          in: query
          type: integer
          format: int32
          description: Number of items to retrieve. Default is 5, maximum is 100.
          required: false
        - name: fields
          in: query
          type: array
          description: 'The fields that should be set in the returned reports defaults 
            to [options, probe_asn, probe_cc, probe_ip, software_name, software_version,
            start_time, test_name, test_version, data_format_version, report_id, test_helpers]'
          items:
            type: string 
        - name: start_date
          in: query
          description: The start date to search reports for.
          required: false
          type: string
          format: date
        - name: end_date
          in: query
          description: The end date to search reports for.
          required: false
          type: string
          format: date
        - name: probe_asn
          in: query
          type: string
          description: The AS Number of the probe (prefixed by AS, ex. AS1234) or null if includeasn is set to false.
          required: false
        - name: probe_cc
          in: query
          type: string
          description: The two letter country code of the probe or null if inlcudecc is set to false.
          required: false
        - name: probe_ip
          in: query
          type: string
          description: The IPv4 address of the probe or null if includeip is set to false.
          required: false
        - name: software_name
          in: query
          type: string
          description: The name of the software that has generated such report (ex. ooniprobe).
          required: false
        - name: software_version
          in: query
          type: string
          description: The version of the software that has generated such report (ex. 0.0.10).
          required: false
        - name: test_name
          in: query
          type: string
          description: The name of the test that such report is for (ex. HTTP Requests).
          required: false
        - name: test_version
          in: query
          type: string
          description: The version of the test that such report is for (ex. 0.0.10).
          required: false
        - name: data_format_version
          in: query
          type: string
          description: The version string of the data format being used by the test (ex. httpt-000)
          required: false
        - name: report_id
          in: query
          type: string
          description: A 64 character mixed case string that is generated by the client used to identify the report.
          required: false
        - name: test_helpers
          in: query
          type: string
          description: A dictionary with as keys the names of the options and values the addresses of the test helpers used.
          required: false
      tags:
        - Open Data
      responses:
        200:
          description: An array of Reports
          schema:
            type: array
            items:
              $ref: '#/definitions/Report'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Report:
    properties:
      options:
        type: string
        description: A dict containing the keys and values of options passed to the test.

      probe_asn:
        type: string
        description: The AS Number of the probe (prefixed by AS, ex. AS1234) or null if includeasn is set to false.

      probe_cc:
        type: string
        description: The two letter country code of the probe or null if inlcudecc is set to false.

      probe_ip:
        type: string
        description: The IPv4 address of the probe or null if includeip is set to false.

      software_name:
        type: string
        description: The name of the software that has generated such report (ex. ooniprobe).

      software_version:
        type: string
        description: The version of the software that has generated such report (ex. 0.0.10).

      start_time:
        type: string
        description: The time at which the test was started in seconds since epoch.

      test_name:
        type: string
        description: The name of the test that such report is for (ex. HTTP Requests).

      test_version:
        type: string
        description: The version of the test that such report is for (ex. 0.0.10).

      data_format_version:
        type: string
        description: The version string of the data format being used by the test (ex. httpt-000)

      report_id:
        type: string
        description: A 64 character mixed case string that is generated by the client used to identify the report.

      measurements:
        type: array
        description: An array of measurements
        items:
          $ref: '#/definitions/Measurement'
 
  Measurement:
    properties:
      start_time:
        type: integer
        format: int32
  Error:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
